---

- include: zabbix_server.yml
  when: zabbix_server_enabled
  tags: [zabbix, zabbix_server]

- include: zabbix_frontend.yml
  when: zabbix_frontend_enabled
  tags: [zabbix, zabbix_frontend]

- include: zabbix_proxy.yml
  when: zabbix_proxy_enabled
  tags: [zabbix, zabbix_proxy]
