---

- name: requirements are present
  apt: name={{ item }} state=present
  with_items:
    - snmp
    - libnet-snmp-perl
    - snmp-mibs-downloader

- name: tmp dir is present
  file: path={{ zabbix_tmpdir }} state=directory

- name: get zabbix-proxy
  get_url: url=http://repo.zabbix.com/zabbix/{{ zabbix_ver.major }}/{{ ansible_lsb.id | lower }}/pool/main/z/zabbix/{{ item.pkg }}_{{ zabbix_ver.major }}.{{ zabbix_ver.minor }}-1+{{ ansible_lsb.codename }}_{{ item.arch }}.deb
           dest={{ zabbix_tmpdir }}/{{ item.pkg }}_{{ zabbix_ver.major }}.{{ zabbix_ver.minor }}-1+{{ ansible_lsb.codename }}_{{ item.arch }}.deb
  with_items:
    - { pkg: zabbix-proxy-mysql, arch: amd64 }

- name: zabbix-proxy-mysql package is present
  apt: deb={{ zabbix_tmpdir }}/{{ item.pkg }}_{{ zabbix_ver.major }}.{{ zabbix_ver.minor }}-1+{{ ansible_lsb.codename }}_{{ item.arch }}.deb
  with_items:
    - { pkg: zabbix-proxy-mysql, arch: amd64 }
  notify: zabbix proxy restart

- name: zabbix_proxy.conf
  template: src={{ zabbix_proxy_conf }}.j2 dest=/etc/zabbix/{{ zabbix_proxy_conf }}
  notify: zabbix proxy restart
  tags: zabbix_conf

- name: include sysctl variables
  include_vars: sysctl.yml

- name: Change various sysctl-settings
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict: sysctl_zabbix

#- name: AlertScripts are in place
#  copy: src={{ item }} dest={{ zabbix_server_AlertScriptsPath }}/
#        owner={{ zabbix_server_user }} group=adm mode=0570
#  with_fileglob:
#    - alertscripts/*
#  tags: 
#    - zabbix_conf
#

##
# Database
##

- name: Provision Application Database
  mysql_db: name={{ db }} state=present
  register: app_db_state
  when: mariadb_enabled

- name: Grant application user access to DB
  mysql_user: name={{ db_user }} priv={{ db }}.*:ALL
              host="localhost" password={{ db_user_password }}
              state=present
  when: mariadb_enabled

#- name: Unarchive Database
#  unarchive: src=/usr/share/doc/zabbix-proxy-mysql/{{ item }}.gz
#             dest=/usr/share/doc/zabbix-proxy-mysql
#             copy=no
#  with_items:
#    - schema.sql

#- name: Unarchive Database
#  command: gzip -d /usr/share/doc/zabbix-proxy-mysql/schema.sql.gz
#  with_items:
#    - schema.sql
#  failed_when: false
#  changed_when: false
#  tags:
#    - dev

- name: Restore Database
  mysql_db: name={{ db }} state=import target=/usr/share/doc/zabbix-proxy-mysql/{{ item }}.gz
            login_user={{ db_user }} login_password={{ db_user_password }}
  with_items:
    - schema.sql
  when: mariadb_enabled and ((app_db_state.changed is defined and app_db_state.changed) or (appdb_creation.changed is defined and appdb_creation.changed))
  #when: mariadb_enabled and app_db_state.changed

##
# Final
##

- name: service is up and running
  service: name=zabbix-proxy state=running

- name: IPMI monitoring for iLO
  include: ipmi_ilo.yml
  when: zabbix_server_ipmi_ilo

- name: Elasticsearch integration
  include: es_integration.yml
  when: zabbix_server_es_integration
  tags: 
    - zabbix_server_es_integration
    - zabbix_server
