---

##
# Database
##

- name: Provision Application Database
  mysql_db: name={{ db }} state=present
  register: app_db_state
  when: mariadb_enabled

- name: Grant application user access to DB
  mysql_user: name={{ db_user }} priv={{ db }}.*:ALL
              host="localhost" password={{ db_user_password }}
              state=present
  when: mariadb_enabled

- name: Restore Database
  mysql_db: name={{ db }} state=import target=/usr/share/doc/zabbix-server-mysql/{{ item }}.gz
            login_user={{ db_user }} login_password={{ db_user_password }}
  with_items:
    - create.sql
  when: mariadb_enabled and app_db_state.changed or (appdb_creation is defined and appdb_creation.changed)

##
# PHP
##

- name: check php.ini
  lineinfile: 
              dest: /etc/php5/fpm/php.ini
              regexp: '{{ item.key }} ='
              line: '{{ item.key }} = {{ item.value }}'
              backrefs: yes
  with_dict: zabbix_php_requirements
  when: php_fpm_enabled is defined and php_fpm_enabled
  notify: php5-fpm restart

- name: check php.ini for hhvm
  lineinfile: 
              dest: /etc/hhvm/php.ini
              insertafter: '; php options'
              regexp: '{{ item.key }} ='
              line: '{{ item.key }} = {{ item.value }}'
              backrefs: no
  with_dict: zabbix_php_requirements
  when: hhvm_enabled is defined and hhvm_enabled
  notify: hhvm restart

- name: check conf dir
  file: path=/etc/zabbix/web/ state=directory
        owner=www-data

- name: app config
  template: src={{ zabbix_conf_php }}.j2 dest=/etc/zabbix/web/{{ zabbix_conf_php }}
            owner=www-data
  when: php_fpm_enabled
  notify: php5-fpm reload

##
# Code
##

- name: app dependensies are present
  apt: pkg=ttf-dejavu-core state=present
  when: app == 'zabbix'


- name: Create www directory
  file: path=/srv/www state=directory owner=root group=root mode=0755

- name: app tmp dir is present
  file: path={{ zabbix_tmpdir }} state=directory

- name: get app
  get_url: url=http://repo.zabbix.com/zabbix/{{ zabbix_ver.major }}/{{ ansible_lsb.id | lower }}/pool/main/z/zabbix/{{ item.pkg }}_{{ zabbix_ver.major }}.{{ zabbix_ver.minor }}-1+{{ ansible_lsb.codename }}_{{ item.arch }}.deb
           dest={{ zabbix_tmpdir }}/{{ item.pkg }}_{{ zabbix_ver.major }}.{{ zabbix_ver.minor }}-1+{{ ansible_lsb.codename }}_{{ item.arch }}.deb
  register: zabbix_frontend_new_ver
  with_items:
    - { pkg: zabbix-frontend-php, arch: all }

- name: app source is present
  command: 'dpkg -x {{ zabbix_tmpdir }}/{{ item.pkg }}_{{ zabbix_ver.major }}.{{ zabbix_ver.minor }}-1+{{ ansible_lsb.codename }}_{{ item.arch }}.deb {{ zabbix_tmpdir }}'
  when: zabbix_frontend_new_ver.changed
  with_items:
    - { pkg: zabbix-frontend-php, arch: all }

- name: app is installed
  command: 'cp -R {{ zabbix_tmpdir }}/usr/share/zabbix/ /srv/www/'
  when: zabbix_frontend_new_ver.changed

- name: app font is present
  command: 'update-alternatives --install /srv/www/{{ app }}/fonts/graphfont.ttf zabbix-frontend-font /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf 10'
  args: { removes: "/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf",
          creates: "/srv/www/{{ app }}/fonts/graphfont.ttf" }

- name: check app tree ownership
  file: path=/srv/www/{{ app }}
        state=directory
        recurse=yes
        owner="www-data" group="adm"
  tags: app_permissions

- name: check permissions for directory tree
  command: 'find /srv/www/{{ app }} -type d -exec chmod 2570 {} \;'
  changed_when: false
  tags: app_permissions

- name: check permissions for files in the tree
  command: 'find /srv/www/{{ app }} -type f -exec chmod 0470 {} \;'
  changed_when: false
  tags: app_permissions

- name: check absence of sgid suid exec bits from all files in the tree
  command: 'find /srv/www/{{ app }} -type f -exec chmod ugo-sx {} \;'
  changed_when: false
  tags: app_permissions
