---

- name: tmp dir is present
  file: path={{ zabbix_tmpdir }} state=directory

- name: get zabbix-agent
  get_url: url=http://repo.zabbix.com/zabbix/{{ zabbix_ver.major }}/{{ ansible_lsb.id | lower }}/pool/main/z/zabbix/{{ item.pkg }}_{{ zabbix_ver.major }}.{{ zabbix_ver.minor }}-1+{{ ansible_lsb.codename }}_{{ item.arch }}.deb
           dest={{ zabbix_tmpdir }}/{{ item.pkg }}.deb
  with_items:
    - { pkg: zabbix-agent, arch: amd64 }

- name: zabbix-agent package is present
  apt: deb={{ zabbix_tmpdir }}/{{ item }}
  with_items:
    - 'zabbix-agent.deb'

- name: zabbix_agentd.conf
  template: src={{ zabbix_agentd_conf }}.j2 dest=/etc/zabbix/{{ zabbix_agentd_conf }}
  notify: zabbix agent restart

- name: zabbix-agent home directory
  file: path=/var/lib/zabbix state=directory
        owner=zabbix group=adm mode=750
  when: mariadb_enabled is defined and mariadb_enabled
  notify: zabbix agent restart
  tags: 
    - my_cnf

- name: zabbix-agent .my.cnf file for DB monitoring
  template: src=my_monitoring.cnf.j2 dest=/var/lib/zabbix/.my.cnf 
            owner=zabbix group=adm mode=0640
  when: mariadb_enabled is defined and mariadb_enabled
        and db_mon_password is defined
  notify: zabbix agent restart
  tags: 
    - my_cnf

- name: service is up and running
  service: name=zabbix-agent state=running
