---

- name: requirements are present
  apt: name={{ item }} state=present
  with_items:
    - snmp
    - libnet-snmp-perl
    - snmp-mibs-downloader

- name: tmp dir is present
  file: path={{ zabbix_tmpdir }} state=directory

- name: check zabbix-server state
  stat: path=/usr/sbin/zabbix_server
  register: zabbix_bin

- name: get zabbix-server
  get_url: url=http://repo.zabbix.com/zabbix/{{ zabbix_ver.major }}/{{ ansible_lsb.id | lower }}/pool/main/z/zabbix/{{ item.pkg }}_{{ zabbix_ver.major }}.{{ zabbix_ver.minor }}-1+{{ ansible_lsb.codename }}_{{ item.arch }}.deb
           dest={{ zabbix_tmpdir }}/{{ item.pkg }}.deb
  with_items:
    - { pkg: zabbix-server-mysql, arch: amd64 }

- name: zabbix-server-mysql package is present
  apt: deb={{ zabbix_tmpdir }}/{{ item }}
  with_items:
    - 'zabbix-server-mysql.deb'

- name: zabbix_server.conf
  template: src={{ zabbix_server_conf }}.j2 dest=/etc/zabbix/{{ zabbix_server_conf }}
  notify: zabbix server restart

- name: service is up and running
  service: name=zabbix-server state=running